[package]
name = 'music'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[dependencies]
anyhow = ''
fehler = ''
lazy_static = ''
serde = ''
serde_derive = '' # 2s
#serde-derive = { package='wa-serde-derive', version='' } # 20s :/
roxmltree = ''
itertools = ''
derive-more = { package='derive_more', version='' }

[dependencies.framework]
path = 'framework'
#git = "https://github.com/Matthias-Fauconneau/framework"
features = ['fehler','anyhow','graphic','window','font-file','trace','signal-hook','timeout']
