package={name='music', version='0.0.0', edition='2021'}

[dependencies]
anyhow='*'
fehler='*'
lazy_static='*'
serde='*'
serde_derive='*'
roxmltree='*'
itertools='*'
derive-more={package='derive_more', version='*'}
ttf-parser='*'
iter={git='https://github.com/Matthias-Fauconneau/iter'}
vector={git='https://github.com/Matthias-Fauconneau/vector'}
xy={git='https://github.com/Matthias-Fauconneau/xy'}
ui={git='https://github.com/Matthias-Fauconneau/ui', features=['graphic']}
