package={name='music', version='0.0.0', edition='2021'}

[dependencies]
assert2='*'
anyhow='*'
fehler='*'
serde='*'
serde_derive='*'
roxmltree='*'
appendlist='*'
itertools='*'
derive-more={package='derive_more', version='*'}
ttf-parser='*'
iter={git='https://github.com/Matthias-Fauconneau/iter'}
num={git='https://github.com/Matthias-Fauconneau/num'}
vector={git='https://github.com/Matthias-Fauconneau/vector'}
xy={git='https://github.com/Matthias-Fauconneau/xy'}
ui={git='https://github.com/Matthias-Fauconneau/ui'}
