[package]
name = 'music'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[dependencies]
anyhow = ''
fehler = ''
lazy_static = ''
serde = ''
serde_derive = '' # 2s
roxmltree = ''
itertools = ''
derive-more = { package='derive_more', version='' }
ttf-parser = ''
core = { version='', path='../core' }
xy = { version='', path='../xy' }
ui = { version='', path='../ui', features=['graphic','text'] }
