[package]
name = 'musicxml'
version = '0.0.0'
authors = ['Matthias Fauconneau <matthias.fauconneau@gmail.com>']
edition = '2018'

[dependencies]
fehler = ''
anyhow = ''
serde = { version = '', features = ['derive'] }
roxmltree = ''
itertools = ''
